/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative */

#ifndef _Included_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
#define _Included_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    init
 * Signature: (Lcn/yezhss/seetaface/po/SeetaModelSetting;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_init
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    predict
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;Lcn/yezhss/seetaface/po/SeetaRect;[Lcn/yezhss/seetaface/po/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_predict
  (JNIEnv *, jclass, jlong, jobject, jobject, jobjectArray);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    predictVideo
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;Lcn/yezhss/seetaface/po/SeetaRect;[Lcn/yezhss/seetaface/po/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_predictVideo
  (JNIEnv *, jclass, jlong, jobject, jobject, jobjectArray);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    resetVideo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_resetVideo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    getPreFrameScore
 * Signature: (J)Lcn/yezhss/seetaface/po/PreFrameScore;
 */
JNIEXPORT jobject JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_getPreFrameScore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    setVideoFrameCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_setVideoFrameCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    getVideoFrameCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_getVideoFrameCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    setThreshold
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_setThreshold
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    setBoxThresh
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_setBoxThresh
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    getBoxThresh
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_getBoxThresh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    getThreshold
 * Signature: (J)Lcn/yezhss/seetaface/po/PreFrameScore;
 */
JNIEXPORT jobject JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_getThreshold
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_set
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    get
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceAntiSpoofingNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
