/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yezhss_seetaface_cxx_QualityOfLBNNative */

#ifndef _Included_cn_yezhss_seetaface_cxx_QualityOfLBNNative
#define _Included_cn_yezhss_seetaface_cxx_QualityOfLBNNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfLBNNative
 * Method:    init
 * Signature: (Lcn/yezhss/seetaface/po/SeetaModelSetting;)J
 */
JNIEXPORT jlong JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfLBNNative_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfLBNNative
 * Method:    detect
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;[Lcn/yezhss/seetaface/po/SeetaPointF;)Lcn/yezhss/seetaface/po/BlurInfo;
 */
JNIEXPORT jobject JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfLBNNative_detect
  (JNIEnv *, jclass, jlong, jobject, jobjectArray);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfLBNNative
 * Method:    set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfLBNNative_set
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfLBNNative
 * Method:    get
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfLBNNative_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfLBNNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfLBNNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
