/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yezhss_seetaface_cxx_GenderPredictorNative */

#ifndef _Included_cn_yezhss_seetaface_cxx_GenderPredictorNative
#define _Included_cn_yezhss_seetaface_cxx_GenderPredictorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yezhss_seetaface_cxx_GenderPredictorNative
 * Method:    init
 * Signature: (Lcn/yezhss/seetaface/po/SeetaModelSetting;)J
 */
JNIEXPORT jlong JNICALL Java_cn_yezhss_seetaface_cxx_GenderPredictorNative_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cn_yezhss_seetaface_cxx_GenderPredictorNative
 * Method:    cropFace
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;[Lcn/yezhss/seetaface/po/SeetaPointF;)Lcn/yezhss/seetaface/po/SeetaImageData;
 */
JNIEXPORT jobject JNICALL Java_cn_yezhss_seetaface_cxx_GenderPredictorNative_cropFace
  (JNIEnv *, jclass, jlong, jobject, jobjectArray);

/*
 * Class:     cn_yezhss_seetaface_cxx_GenderPredictorNative
 * Method:    predictGender
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;)I
 */
JNIEXPORT jint JNICALL Java_cn_yezhss_seetaface_cxx_GenderPredictorNative_predictGender
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     cn_yezhss_seetaface_cxx_GenderPredictorNative
 * Method:    predictGenderWithCrop
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;[Lcn/yezhss/seetaface/po/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_cn_yezhss_seetaface_cxx_GenderPredictorNative_predictGenderWithCrop
  (JNIEnv *, jclass, jlong, jobject, jobjectArray);

/*
 * Class:     cn_yezhss_seetaface_cxx_GenderPredictorNative
 * Method:    set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_GenderPredictorNative_set
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     cn_yezhss_seetaface_cxx_GenderPredictorNative
 * Method:    get
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_yezhss_seetaface_cxx_GenderPredictorNative_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_GenderPredictorNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_GenderPredictorNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
