/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yezhss_seetaface_cxx_FaceTrackerNative */

#ifndef _Included_cn_yezhss_seetaface_cxx_FaceTrackerNative
#define _Included_cn_yezhss_seetaface_cxx_FaceTrackerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    init
 * Signature: (Lcn/yezhss/seetaface/po/SeetaModelSetting;II)J
 */
JNIEXPORT jlong JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_init
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    setSingleCalculationThreads
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_setSingleCalculationThreads
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    track
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;I)Lcn/yezhss/seetaface/po/SeetaTrackingFaceInfoArray;
 */
JNIEXPORT jobject JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_track
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    setMinFaceSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_setMinFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    getMinFaceSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_getMinFaceSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    setThreshold
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_setThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    getThreshold
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_getThreshold
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    setVideoStable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_setVideoStable
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    getVideoStable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_getVideoStable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_yezhss_seetaface_cxx_FaceTrackerNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_FaceTrackerNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
