/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yezhss_seetaface_cxx_QualityOfPoseExNative */

#ifndef _Included_cn_yezhss_seetaface_cxx_QualityOfPoseExNative
#define _Included_cn_yezhss_seetaface_cxx_QualityOfPoseExNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfPoseExNative
 * Method:    init
 * Signature: (Lcn/yezhss/seetaface/po/SeetaModelSetting;)J
 */
JNIEXPORT jlong JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfPoseExNative_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfPoseExNative
 * Method:    check
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;Lcn/yezhss/seetaface/po/SeetaRect;[Lcn/yezhss/seetaface/po/SeetaPointF;)Lcn/yezhss/seetaface/po/QualityResult;
 */
JNIEXPORT jobject JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfPoseExNative_check
  (JNIEnv *, jclass, jlong, jobject, jobject, jobjectArray);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfPoseExNative
 * Method:    set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfPoseExNative_set
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfPoseExNative
 * Method:    get
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfPoseExNative_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfPoseExNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfPoseExNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
