/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yezhss_seetaface_cxx_QualityOfBrightnessNative */

#ifndef _Included_cn_yezhss_seetaface_cxx_QualityOfBrightnessNative
#define _Included_cn_yezhss_seetaface_cxx_QualityOfBrightnessNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfBrightnessNative
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfBrightnessNative_init__
  (JNIEnv *, jclass);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfBrightnessNative
 * Method:    init
 * Signature: (FFFF)J
 */
JNIEXPORT jlong JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfBrightnessNative_init__FFFF
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfBrightnessNative
 * Method:    check
 * Signature: (JLcn/yezhss/seetaface/po/SeetaImageData;Lcn/yezhss/seetaface/po/SeetaRect;[Lcn/yezhss/seetaface/po/SeetaPointF;)Lcn/yezhss/seetaface/po/QualityResult;
 */
JNIEXPORT jobject JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfBrightnessNative_check
  (JNIEnv *, jclass, jlong, jobject, jobject, jobjectArray);

/*
 * Class:     cn_yezhss_seetaface_cxx_QualityOfBrightnessNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cn_yezhss_seetaface_cxx_QualityOfBrightnessNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
